#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""把 page/index.html 内嵌成 src/index_html.h（改页必跑，漏跑会静默打进旧页面）。

输出符号：
    static const unsigned char index_html[] = { ... };
    static const unsigned int  index_html_len  = NNN;

字节原样嵌入（UTF-8），不转义字符串，避免 C 字符串字面量的长度上限。

★ R1.2.0（FB-015）：固化前先断言「页面 meta 版本 == src/version.h 的 MOINK_VERSION」。
   版本号统一成一套之后，两处一旦漂移就又变回两套号 —— 这个断言就是防漂移闸门，
   不一致直接 exit 1，并打印两边实际值。
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "page", "index.html")
VH = os.path.join(ROOT, "src", "version.h")
DST = os.path.join(ROOT, "src", "index_html.h")

META_RE = re.compile(r'<meta\s+name="moink-page-version"\s+content="([^"]+)"')
VER_RE = re.compile(r'#define\s+MOINK_VERSION\s+"([^"]+)"')


def main():
    data = open(SRC, "rb").read()
    text = data.decode("utf-8")

    m_page = META_RE.search(text)
    m_hdr = VER_RE.search(open(VH, encoding="utf-8").read())
    if not m_page or not m_hdr:
        print("!! 版本号取不到：页面 meta=%s / version.h MOINK_VERSION=%s"
              % (bool(m_page), bool(m_hdr)))
        return 1
    page_ver, hdr_ver = m_page.group(1), m_hdr.group(1)
    if page_ver != hdr_ver:
        print("!! 版本号不一致，拒绝固化：")
        print("     page/index.html  <meta moink-page-version> = %s" % page_ver)
        print("     src/version.h    MOINK_VERSION              = %s" % hdr_ver)
        print("   统一版本号之后两处必须相同，改齐再跑。")
        return 1

    n = len(data)
    lines = []
    lines.append("/* auto-generated by tools/make_index_header.py - do not edit */")
    lines.append("static const unsigned char index_html[] = {")
    for i in range(0, n, 16):
        chunk = data[i:i + 16]
        lines.append("    " + ",".join("0x%02x" % b for b in chunk) + ",")
    lines.append("};")
    lines.append("static const unsigned int index_html_len = %d;" % n)
    lines.append("")

    open(DST, "w", encoding="ascii").write("\n".join(lines))
    print("wrote %s (%d bytes, ver %s) -> %s" % (SRC, n, hdr_ver, DST))
    return 0


if __name__ == "__main__":
    sys.exit(main())
